/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _tests___rootTestRouteImport } from './routes/__tests__/__root.test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangCoursesRouteImport } from './routes/$lang.courses'
import { Route as _tests_IndexTestRouteImport } from './routes/__tests__/index.test'
import { Route as LangCoursesIndexRouteImport } from './routes/$lang.courses.index'
import { Route as LangCoursesCourseIdRouteImport } from './routes/$lang.courses.$courseId'
import { Route as LangCoursesCourseIdIndexRouteImport } from './routes/$lang.courses.$courseId.index'
import { Route as LangCoursesCourseIdSubjectRouteImport } from './routes/$lang.courses.$courseId.$subject'
import { Route as _tests_LangCoursesIndexTestRouteImport } from './routes/__tests__/$lang.courses.index.test'
import { Route as LangCoursesCourseIdSubjectIndexRouteImport } from './routes/$lang.courses.$courseId.$subject.index'
import { Route as LangCoursesCourseIdSubjectLevelRouteImport } from './routes/$lang.courses.$courseId.$subject.$level'
import { Route as _tests_LangCoursesCourseIdIndexTestRouteImport } from './routes/__tests__/$lang.courses.$courseId.index.test'
import { Route as _tests_LangCoursesCourseIdSubjectIndexTestRouteImport } from './routes/__tests__/$lang.courses.$courseId.$subject.index.test'
import { Route as _tests_LangCoursesCourseIdSubjectLevelTestRouteImport } from './routes/__tests__/$lang.courses.$courseId.$subject.$level.test'

const _tests___rootTestRoute = _tests___rootTestRouteImport.update({
  id: '/__tests__/__root/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangCoursesRoute = LangCoursesRouteImport.update({
  id: '/$lang/courses',
  path: '/$lang/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const _tests_IndexTestRoute = _tests_IndexTestRouteImport.update({
  id: '/__tests__/index/test',
  path: '/index/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LangCoursesIndexRoute = LangCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangCoursesRoute,
} as any)
const LangCoursesCourseIdRoute = LangCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => LangCoursesRoute,
} as any)
const LangCoursesCourseIdIndexRoute =
  LangCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangCoursesCourseIdRoute,
  } as any)
const LangCoursesCourseIdSubjectRoute =
  LangCoursesCourseIdSubjectRouteImport.update({
    id: '/$subject',
    path: '/$subject',
    getParentRoute: () => LangCoursesCourseIdRoute,
  } as any)
const _tests_LangCoursesIndexTestRoute =
  _tests_LangCoursesIndexTestRouteImport.update({
    id: '/__tests__/$lang/courses/index/test',
    path: '/$lang/courses/index/test',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangCoursesCourseIdSubjectIndexRoute =
  LangCoursesCourseIdSubjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LangCoursesCourseIdSubjectRoute,
  } as any)
const LangCoursesCourseIdSubjectLevelRoute =
  LangCoursesCourseIdSubjectLevelRouteImport.update({
    id: '/$level',
    path: '/$level',
    getParentRoute: () => LangCoursesCourseIdSubjectRoute,
  } as any)
const _tests_LangCoursesCourseIdIndexTestRoute =
  _tests_LangCoursesCourseIdIndexTestRouteImport.update({
    id: '/__tests__/$lang/courses/$courseId/index/test',
    path: '/$lang/courses/$courseId/index/test',
    getParentRoute: () => rootRouteImport,
  } as any)
const _tests_LangCoursesCourseIdSubjectIndexTestRoute =
  _tests_LangCoursesCourseIdSubjectIndexTestRouteImport.update({
    id: '/__tests__/$lang/courses/$courseId/$subject/index/test',
    path: '/$lang/courses/$courseId/$subject/index/test',
    getParentRoute: () => rootRouteImport,
  } as any)
const _tests_LangCoursesCourseIdSubjectLevelTestRoute =
  _tests_LangCoursesCourseIdSubjectLevelTestRouteImport.update({
    id: '/__tests__/$lang/courses/$courseId/$subject/$level/test',
    path: '/$lang/courses/$courseId/$subject/$level/test',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/courses': typeof LangCoursesRouteWithChildren
  '/$lang/courses/$courseId': typeof LangCoursesCourseIdRouteWithChildren
  '/test': typeof _tests___rootTestRoute
  '/$lang/courses/': typeof LangCoursesIndexRoute
  '/index/test': typeof _tests_IndexTestRoute
  '/$lang/courses/$courseId/$subject': typeof LangCoursesCourseIdSubjectRouteWithChildren
  '/$lang/courses/$courseId/': typeof LangCoursesCourseIdIndexRoute
  '/$lang/courses/$courseId/$subject/$level': typeof LangCoursesCourseIdSubjectLevelRoute
  '/$lang/courses/$courseId/$subject/': typeof LangCoursesCourseIdSubjectIndexRoute
  '/$lang/courses/index/test': typeof _tests_LangCoursesIndexTestRoute
  '/$lang/courses/$courseId/index/test': typeof _tests_LangCoursesCourseIdIndexTestRoute
  '/$lang/courses/$courseId/$subject/$level/test': typeof _tests_LangCoursesCourseIdSubjectLevelTestRoute
  '/$lang/courses/$courseId/$subject/index/test': typeof _tests_LangCoursesCourseIdSubjectIndexTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof _tests___rootTestRoute
  '/$lang/courses': typeof LangCoursesIndexRoute
  '/index/test': typeof _tests_IndexTestRoute
  '/$lang/courses/$courseId': typeof LangCoursesCourseIdIndexRoute
  '/$lang/courses/$courseId/$subject/$level': typeof LangCoursesCourseIdSubjectLevelRoute
  '/$lang/courses/$courseId/$subject': typeof LangCoursesCourseIdSubjectIndexRoute
  '/$lang/courses/index/test': typeof _tests_LangCoursesIndexTestRoute
  '/$lang/courses/$courseId/index/test': typeof _tests_LangCoursesCourseIdIndexTestRoute
  '/$lang/courses/$courseId/$subject/$level/test': typeof _tests_LangCoursesCourseIdSubjectLevelTestRoute
  '/$lang/courses/$courseId/$subject/index/test': typeof _tests_LangCoursesCourseIdSubjectIndexTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/courses': typeof LangCoursesRouteWithChildren
  '/$lang/courses/$courseId': typeof LangCoursesCourseIdRouteWithChildren
  '/__tests__/__root/test': typeof _tests___rootTestRoute
  '/$lang/courses/': typeof LangCoursesIndexRoute
  '/__tests__/index/test': typeof _tests_IndexTestRoute
  '/$lang/courses/$courseId/$subject': typeof LangCoursesCourseIdSubjectRouteWithChildren
  '/$lang/courses/$courseId/': typeof LangCoursesCourseIdIndexRoute
  '/$lang/courses/$courseId/$subject/$level': typeof LangCoursesCourseIdSubjectLevelRoute
  '/$lang/courses/$courseId/$subject/': typeof LangCoursesCourseIdSubjectIndexRoute
  '/__tests__/$lang/courses/index/test': typeof _tests_LangCoursesIndexTestRoute
  '/__tests__/$lang/courses/$courseId/index/test': typeof _tests_LangCoursesCourseIdIndexTestRoute
  '/__tests__/$lang/courses/$courseId/$subject/$level/test': typeof _tests_LangCoursesCourseIdSubjectLevelTestRoute
  '/__tests__/$lang/courses/$courseId/$subject/index/test': typeof _tests_LangCoursesCourseIdSubjectIndexTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/courses'
    | '/$lang/courses/$courseId'
    | '/test'
    | '/$lang/courses/'
    | '/index/test'
    | '/$lang/courses/$courseId/$subject'
    | '/$lang/courses/$courseId/'
    | '/$lang/courses/$courseId/$subject/$level'
    | '/$lang/courses/$courseId/$subject/'
    | '/$lang/courses/index/test'
    | '/$lang/courses/$courseId/index/test'
    | '/$lang/courses/$courseId/$subject/$level/test'
    | '/$lang/courses/$courseId/$subject/index/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/$lang/courses'
    | '/index/test'
    | '/$lang/courses/$courseId'
    | '/$lang/courses/$courseId/$subject/$level'
    | '/$lang/courses/$courseId/$subject'
    | '/$lang/courses/index/test'
    | '/$lang/courses/$courseId/index/test'
    | '/$lang/courses/$courseId/$subject/$level/test'
    | '/$lang/courses/$courseId/$subject/index/test'
  id:
    | '__root__'
    | '/'
    | '/$lang/courses'
    | '/$lang/courses/$courseId'
    | '/__tests__/__root/test'
    | '/$lang/courses/'
    | '/__tests__/index/test'
    | '/$lang/courses/$courseId/$subject'
    | '/$lang/courses/$courseId/'
    | '/$lang/courses/$courseId/$subject/$level'
    | '/$lang/courses/$courseId/$subject/'
    | '/__tests__/$lang/courses/index/test'
    | '/__tests__/$lang/courses/$courseId/index/test'
    | '/__tests__/$lang/courses/$courseId/$subject/$level/test'
    | '/__tests__/$lang/courses/$courseId/$subject/index/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangCoursesRoute: typeof LangCoursesRouteWithChildren
  _tests___rootTestRoute: typeof _tests___rootTestRoute
  _tests_IndexTestRoute: typeof _tests_IndexTestRoute
  _tests_LangCoursesIndexTestRoute: typeof _tests_LangCoursesIndexTestRoute
  _tests_LangCoursesCourseIdIndexTestRoute: typeof _tests_LangCoursesCourseIdIndexTestRoute
  _tests_LangCoursesCourseIdSubjectLevelTestRoute: typeof _tests_LangCoursesCourseIdSubjectLevelTestRoute
  _tests_LangCoursesCourseIdSubjectIndexTestRoute: typeof _tests_LangCoursesCourseIdSubjectIndexTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__tests__/__root/test': {
      id: '/__tests__/__root/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof _tests___rootTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/courses': {
      id: '/$lang/courses'
      path: '/$lang/courses'
      fullPath: '/$lang/courses'
      preLoaderRoute: typeof LangCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__tests__/index/test': {
      id: '/__tests__/index/test'
      path: '/index/test'
      fullPath: '/index/test'
      preLoaderRoute: typeof _tests_IndexTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/courses/': {
      id: '/$lang/courses/'
      path: '/'
      fullPath: '/$lang/courses/'
      preLoaderRoute: typeof LangCoursesIndexRouteImport
      parentRoute: typeof LangCoursesRoute
    }
    '/$lang/courses/$courseId': {
      id: '/$lang/courses/$courseId'
      path: '/$courseId'
      fullPath: '/$lang/courses/$courseId'
      preLoaderRoute: typeof LangCoursesCourseIdRouteImport
      parentRoute: typeof LangCoursesRoute
    }
    '/$lang/courses/$courseId/': {
      id: '/$lang/courses/$courseId/'
      path: '/'
      fullPath: '/$lang/courses/$courseId/'
      preLoaderRoute: typeof LangCoursesCourseIdIndexRouteImport
      parentRoute: typeof LangCoursesCourseIdRoute
    }
    '/$lang/courses/$courseId/$subject': {
      id: '/$lang/courses/$courseId/$subject'
      path: '/$subject'
      fullPath: '/$lang/courses/$courseId/$subject'
      preLoaderRoute: typeof LangCoursesCourseIdSubjectRouteImport
      parentRoute: typeof LangCoursesCourseIdRoute
    }
    '/__tests__/$lang/courses/index/test': {
      id: '/__tests__/$lang/courses/index/test'
      path: '/$lang/courses/index/test'
      fullPath: '/$lang/courses/index/test'
      preLoaderRoute: typeof _tests_LangCoursesIndexTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/courses/$courseId/$subject/': {
      id: '/$lang/courses/$courseId/$subject/'
      path: '/'
      fullPath: '/$lang/courses/$courseId/$subject/'
      preLoaderRoute: typeof LangCoursesCourseIdSubjectIndexRouteImport
      parentRoute: typeof LangCoursesCourseIdSubjectRoute
    }
    '/$lang/courses/$courseId/$subject/$level': {
      id: '/$lang/courses/$courseId/$subject/$level'
      path: '/$level'
      fullPath: '/$lang/courses/$courseId/$subject/$level'
      preLoaderRoute: typeof LangCoursesCourseIdSubjectLevelRouteImport
      parentRoute: typeof LangCoursesCourseIdSubjectRoute
    }
    '/__tests__/$lang/courses/$courseId/index/test': {
      id: '/__tests__/$lang/courses/$courseId/index/test'
      path: '/$lang/courses/$courseId/index/test'
      fullPath: '/$lang/courses/$courseId/index/test'
      preLoaderRoute: typeof _tests_LangCoursesCourseIdIndexTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__tests__/$lang/courses/$courseId/$subject/index/test': {
      id: '/__tests__/$lang/courses/$courseId/$subject/index/test'
      path: '/$lang/courses/$courseId/$subject/index/test'
      fullPath: '/$lang/courses/$courseId/$subject/index/test'
      preLoaderRoute: typeof _tests_LangCoursesCourseIdSubjectIndexTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__tests__/$lang/courses/$courseId/$subject/$level/test': {
      id: '/__tests__/$lang/courses/$courseId/$subject/$level/test'
      path: '/$lang/courses/$courseId/$subject/$level/test'
      fullPath: '/$lang/courses/$courseId/$subject/$level/test'
      preLoaderRoute: typeof _tests_LangCoursesCourseIdSubjectLevelTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LangCoursesCourseIdSubjectRouteChildren {
  LangCoursesCourseIdSubjectLevelRoute: typeof LangCoursesCourseIdSubjectLevelRoute
  LangCoursesCourseIdSubjectIndexRoute: typeof LangCoursesCourseIdSubjectIndexRoute
}

const LangCoursesCourseIdSubjectRouteChildren: LangCoursesCourseIdSubjectRouteChildren =
  {
    LangCoursesCourseIdSubjectLevelRoute: LangCoursesCourseIdSubjectLevelRoute,
    LangCoursesCourseIdSubjectIndexRoute: LangCoursesCourseIdSubjectIndexRoute,
  }

const LangCoursesCourseIdSubjectRouteWithChildren =
  LangCoursesCourseIdSubjectRoute._addFileChildren(
    LangCoursesCourseIdSubjectRouteChildren,
  )

interface LangCoursesCourseIdRouteChildren {
  LangCoursesCourseIdSubjectRoute: typeof LangCoursesCourseIdSubjectRouteWithChildren
  LangCoursesCourseIdIndexRoute: typeof LangCoursesCourseIdIndexRoute
}

const LangCoursesCourseIdRouteChildren: LangCoursesCourseIdRouteChildren = {
  LangCoursesCourseIdSubjectRoute: LangCoursesCourseIdSubjectRouteWithChildren,
  LangCoursesCourseIdIndexRoute: LangCoursesCourseIdIndexRoute,
}

const LangCoursesCourseIdRouteWithChildren =
  LangCoursesCourseIdRoute._addFileChildren(LangCoursesCourseIdRouteChildren)

interface LangCoursesRouteChildren {
  LangCoursesCourseIdRoute: typeof LangCoursesCourseIdRouteWithChildren
  LangCoursesIndexRoute: typeof LangCoursesIndexRoute
}

const LangCoursesRouteChildren: LangCoursesRouteChildren = {
  LangCoursesCourseIdRoute: LangCoursesCourseIdRouteWithChildren,
  LangCoursesIndexRoute: LangCoursesIndexRoute,
}

const LangCoursesRouteWithChildren = LangCoursesRoute._addFileChildren(
  LangCoursesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangCoursesRoute: LangCoursesRouteWithChildren,
  _tests___rootTestRoute: _tests___rootTestRoute,
  _tests_IndexTestRoute: _tests_IndexTestRoute,
  _tests_LangCoursesIndexTestRoute: _tests_LangCoursesIndexTestRoute,
  _tests_LangCoursesCourseIdIndexTestRoute:
    _tests_LangCoursesCourseIdIndexTestRoute,
  _tests_LangCoursesCourseIdSubjectLevelTestRoute:
    _tests_LangCoursesCourseIdSubjectLevelTestRoute,
  _tests_LangCoursesCourseIdSubjectIndexTestRoute:
    _tests_LangCoursesCourseIdSubjectIndexTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
